### ISSUE TITLE
Literal string to identify package public namespace

### ISSUE THREAD

**Issue by Klaider** [apache/royale-compiler#100]
Currently, aliasing package with namespace definition is requiring a wildcard import.

This could be improved by the following steps:
1. Let _p_ be any package whose full name equals the literal string.
2. If _p_ is undefined:
  a. Verify the namespace definition as an explicit URI namespace.
  b. Return.
3. Behave as if a directive `import p.*` were inserted before the namespace definition, however do not push the `public` namespace to the open namespace list.
4. Define `internal::[namespaceName]` as the `public` namespace of _p_.

**Comment by joshtynjala** [comment]
I tried compiling the following code with the Apache Flex SDK 4.16.1 and AIR SDK 32.0.0.89, and they don't behave the same. The Flex SDK compiles successfully, but ASC 2.0 reports an error.

```actionscript
package
{
	import flash.display.MovieClip;

	public class FlashPackageAsNamespace extends MovieClip
	{
		public function FlashPackageAsNamespace()
		{
			namespace dispns = 'flash.display'
			new dispns::Sprite
		}
	}
}
```

Error reported by ASC 2.0:

> FlashPackageAsNamespace.as:10
> Error: Call to a possibly undefined method Sprite.
>                        new dispns::Sprite

The Royale compiler behaves similarly to ASC 2.0, which obviously makes sense since it was originally forked from ASC 2.0.

**Comment by joshtynjala** [comment]
I can reproduce the crash when annotating a type with a namespace. Stack trace copied below for future reference:

```
java.lang.ClassCastException: class org.apache.royale.compiler.internal.tree.as.NamespaceAccessExpressionNode cannot be cast to class org.apache.royale.compiler.tree.as.IIdentifierNode (org.apache.royale.compiler.internal.tree.as.NamespaceAccessExpressionNode and org.apache.royale.compiler.tree.as.IIdentifierNode are in unnamed module of loader 'app')
	at org.apache.royale.compiler.internal.tree.as.BaseTypedDefinitionNode.getTypeName(BaseTypedDefinitionNode.java:127)
	at org.apache.royale.compiler.internal.semantics.MethodBodySemanticChecker.checkVariableDeclaration(MethodBodySemanticChecker.java:2579)
	at org.apache.royale.compiler.internal.as.codegen.ABCGeneratingReducer.reduce_typedVariableDecl(ABCGeneratingReducer.java:6022)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.action_465(CmcEmitter.java:6490)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.dispatchAction(CmcEmitter.java:9207)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceAntecedent(CmcEmitter.java:39127)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.dispatchAction(CmcEmitter.java:9410)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceAntecedent(CmcEmitter.java:39127)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduce(CmcEmitter.java:39104)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceSubgoals(CmcEmitter.java:39155)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceAntecedent(CmcEmitter.java:39126)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduce(CmcEmitter.java:39104)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceSubgoals(CmcEmitter.java:39146)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceAntecedent(CmcEmitter.java:39126)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduce(CmcEmitter.java:39104)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.burm(CmcEmitter.java:39406)
	at org.apache.royale.compiler.internal.as.codegen.ABCGenerator.generateInstructions(ABCGenerator.java:234)
	at org.apache.royale.compiler.internal.as.codegen.ABCGenerator.generateMethodBodyForFunction(ABCGenerator.java:399)
	at org.apache.royale.compiler.internal.as.codegen.ABCGenerator.generateMethodBodyForFunction(ABCGenerator.java:353)
	at org.apache.royale.compiler.internal.as.codegen.ABCGenerator.generateFunction(ABCGenerator.java:268)
	at org.apache.royale.compiler.internal.as.codegen.ClassDirectiveProcessor.finishClassDefinition(ClassDirectiveProcessor.java:617)
	at org.apache.royale.compiler.internal.as.codegen.GlobalDirectiveProcessor.declareClass(GlobalDirectiveProcessor.java:463)
	at org.apache.royale.compiler.internal.as.codegen.DirectiveProcessor.processNode(DirectiveProcessor.java:210)
	at org.apache.royale.compiler.internal.as.codegen.DirectiveProcessor.traverse(DirectiveProcessor.java:192)
	at org.apache.royale.compiler.internal.as.codegen.GlobalDirectiveProcessor.declarePackage(GlobalDirectiveProcessor.java:488)
	at org.apache.royale.compiler.internal.as.codegen.DirectiveProcessor.processNode(DirectiveProcessor.java:227)
	at org.apache.royale.compiler.internal.as.codegen.DirectiveProcessor.traverse(DirectiveProcessor.java:192)
	at org.apache.royale.compiler.internal.as.codegen.ABCGenerator.generate(ABCGenerator.java:125)
	at org.apache.royale.compiler.internal.units.ASCompilationUnit.handleABCBytesRequest(ASCompilationUnit.java:395)
	at org.apache.royale.compiler.internal.units.CompilationUnitBase.processABCBytesRequest(CompilationUnitBase.java:876)
	at org.apache.royale.compiler.internal.units.CompilationUnitBase.access$300(CompilationUnitBase.java:109)
	at org.apache.royale.compiler.internal.units.CompilationUnitBase$4$1.call(CompilationUnitBase.java:313)
	at org.apache.royale.compiler.internal.units.CompilationUnitBase$4$1.call(CompilationUnitBase.java:309)
	at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228)
	at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by joshtynjala** [comment]
As best I can tell, Adobe actually intended for ASC 2.0 to be unable to allow a namespace defined in ActionScript code to access a package.

Inside the compiler code, all namespaces have a "kind", and there are several of these kinds. There's a kind for namespaces defined in ActionScript code, a kind for protected, a kind for private, a kind for packages, and some others.

The code that determines if two namespaces are equal requires that the "kind" of both namespaces is also equal. So, a namespace defined in ActionScript code (`ABCConstants.CONSTANT_Namespace`) can never be equal to a package namespace (`ABCConstants.CONSTANT_PackageNs`).

To me this does not seem like something that should have a special exception. It seems like the Adobe engineers designed it to work this way on purpose. In fact, there are a number of differences between ASC 2.0 and the original Flex SDK compiler that makes ASC 2.0 more strict, much like this.

Just out of curiosity, have you discovered a use for this behavior that would otherwise be impossible by importing the type instead?

**Comment by Hydroper** [comment]
The purpose would be to improve readability in large programs. In C# or Rust you have these directives:

```rust
use foo::lib::utils as qux;
```

```C#
import Qux = Foo.Lib.Utils;
```

In ActionScript, because there is not something like `import qux = foo.library.utils.*`, programs where scope has lexical conflicting names (like `package1.Item` and `package2.Item`) the programmer must use the fully package-qualified names.

For certain compiler writting methods, it is good, for instance, to know what belongs to semantic data model and what belongs to bytecode structure. (In my mind, I reflect names such as `sem::Activation`, `bc_ns::MetaData`).

> The code that determines if two namespaces are equal requires that the "kind" of both namespaces is also equal. So, a namespace defined in ActionScript code (`ABCConstants.CONSTANT_Namespace`) can never be equal to a package namespace (`ABCConstants.CONSTANT_PackageNs`).

For most cases, when namespaces are represented as heap objects, pooling explicit namespaces (except these of anonymous identity such as `namespace ns`) and comparing by reference should work.

**Comment by Hydroper** [comment]
I've just tested too Flex SDK 4.16.1 and it supports qualified type nodes as well. To use these features in Adobe AIR one then needs to replace the compiler base by the Flex SDK one.

**Comment by greg-dove** [comment]
Did you already try with this in Royale?:
import Alias = com.example.ClassToImport

Josh added that a few years ago, iirc.

**Comment by Hydroper** [comment]
I was not aware of it, but I was wanting this syntax for aliasing the public `namespace` as well, adding a wildcard, such as in:

```as
import alias = com.vendor.foolibrary.diverse.*
```

This would import the package `com.vendor.foolibrary.diverse` and put the `public` namespace in scope (as `alias`).

**Comment by Hydroper** [comment]
Currently, aliasing package with namespace definition is requiring a wildcard import.

This could be improved by the following steps:
1. Let _p_ be any package whose full name equals the literal string.
2. If _p_ is `null`:
  a. Verify the namespace definition as an explicit URI namespace.
  b. Return.
3. Behave as if a directive `import p.*` were inserted before the namespace definition.
4. Define `internal::[namespaceName]` as the `public` namespace of _p_.

**Comment by carlosrovira** [comment]
Hi @Hydroper, maybe I'm wrong, but if you know the steps to solve the issue, can't you provide a PR so others can check if is valid and then merge it? Apache Royale is OS community project, we expect other submitting patches and eventually be committers in order to grow. Others are already doing this.

Thanks
