### ISSUE TITLE
Internal Error in ASBlockWalker subsystem

### ISSUE THREAD

**Issue by Laturine** [apache/royale-compiler#178]
Hi I'm currently migrating an app from Flex and fixed all the compiler errors, but then ran into this internal error. The mxml file in question is 1700 lines and defines many methods and remoteObjects.

I recieved the same error using both 0.9.7 and 0.9.8 sdk's.

Any help would be appreciated. Thanks! 
```
Error: Internal error in ASBlockWalker subsystem, when generating code for: C:\Users\developer\Downloads\apache-royale-0.9.7-bin-js-swf\royale-asjs\examples\mxroyale\HelloWorld\src\main\royale\com\icius\planit\common\business\PlanITServices.mxml line 1232 column 1: java.lang.NullPointerException
: 	at org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyaleEmitter.emitRemoteObject(MXMLRoyaleEmitter.java:3998)
: 	at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.visitRemoteObject(MXMLBlockWalker.java:470)
: 	at org.apache.royale.compiler.internal.visitor.mxml.MXMLNodeSwitch.handle(MXMLNodeSwitch.java:168)
: 	at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.walk(MXMLBlockWalker.java:156)
: 	at org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyaleEmitter.emitDocument(MXMLRoyaleEmitter.java:877)
: 	at org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyaleBlockWalker.visitDocument(MXMLRoyaleBlockWalker.java:69)
: 	at org.apache.royale.compiler.internal.visitor.mxml.MXMLNodeSwitch.handle(MXMLNodeSwitch.java:89)
: 	at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.walk(MXMLBlockWalker.java:156)
: 	at org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyaleBlockWalker.visitFile(MXMLRoyaleBlockWalker.java:61)
: 	at org.apache.royale.compiler.internal.visitor.mxml.MXMLNodeSwitch.handle(MXMLNodeSwitch.java:95)
: 	at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.walk(MXMLBlockWalker.java:156)
: 	at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.visitCompilationUnit(MXMLBlockWalker.java:187)
: 	at org.apache.royale.compiler.internal.codegen.mxml.MXMLWriter.writeTo(MXMLWriter.java:69)
: 	at org.apache.royale.compiler.clients.MXMLJSCRoyale.compile(MXMLJSCRoyale.java:411)
: 	at org.apache.royale.compiler.clients.MXMLJSCRoyale._mainNoExit(MXMLJSCRoyale.java:259)
: 	at org.apache.royale.compiler.clients.MXMLJSCRoyale.mainNoExit(MXMLJSCRoyale.java:216)
: 	at org.apache.royale.compiler.clients.MXMLJSC._mainNoExit(MXMLJSC.java:363)
: 	at org.apache.royale.compiler.clients.MXMLJSC.mainNoExit(MXMLJSC.java:298)
: 	at org.apache.royale.compiler.clients.MXMLJSC.staticMainNoExit(MXMLJSC.java:256)
: 	at org.apache.royale.compiler.clients.MXMLJSC.main(MXMLJSC.java:238)
```

**Comment by Laturine** [comment]
This appears to be caused by <mx:method/> with the mxml structure being
<mx:RemoteObject>
  <mx:method/>
</mx:RemoteObject>

**Comment by joshtynjala** [comment]
I just fixed a number of issues parsing RemoteObject `<mx:method>`  and WebService `<mx:operation>` (along with `<mx:arguments>`), and parsing HTTPService `<mx:request>`. I wasn't able to get a null exception, but I suspect that my new code is more robust. So I'm calling it fixed. This work will be included in the next update.
