### ISSUE TITLE
ABC generator Subsystem Error

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-compiler#54]
D:\apache-royale-0.9.3-bin-js-swf\royale-asjs\examples\mxroyale\Final Project\library\src\com\shm\modules\Common\shmFreightFactorCalculationSetup.mxml 
 
Internal error in ABC generator subsystem, when generating code for: D:\apache-royale-0.9.3-bin-js-swf\royale-asjs\examples\mxroyale\Fina
brary\src\com\shm\modules\Common\shmFreightFactorCalculationSetup.mxml: java.lang.NullPointerException
 
 
 
    at org.antlr.runtime.tree.BaseTreeAdaptor.isNil(BaseTreeAdaptor.java:73)
    at org.antlr.runtime.tree.CommonTreeNodeStream.nextElement(CommonTreeNodeStream.java:104)
    at org.antlr.runtime.misc.LookaheadStream.fill(LookaheadStream.java:113)
    at org.antlr.runtime.misc.LookaheadStream.syncAhead(LookaheadStream.java:107)
    at org.antlr.runtime.misc.LookaheadStream.LT(LookaheadStream.java:129)
    at org.apache.royale.compiler.internal.css.CSSTree.stylesheet(CSSTree.java:204)
    at org.apache.royale.compiler.internal.css.CSSDocument.parse(CSSDocument.java:81)
    at org.apache.royale.compiler.internal.tree.mxml.MXMLStyleNode.getCSSDocument(MXMLStyleNode.java:94)
    at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.processMXMLStyle(MXMLClassDirectiveProcessor.java:4322)
    at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.processNode(MXMLClassDirectiveProcessor.java:990)
    at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.traverse(MXMLClassDirectiveProcessor.java:864)
    at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.traverse(MXMLClassDirectiveProcessor.java:834)
    at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.processMainClassDefinitionNode(MXMLClassDirectiveProcessor.java:656)
    at org.apache.royale.compiler.internal.as.codegen.GlobalDirectiveProcessor.declareMXMLDocument(GlobalDirectiveProcessor.java:518)
    at org.apache.royale.compiler.internal.as.codegen.DirectiveProcessor.processNode(DirectiveProcessor.java:237)
    at org.apache.royale.compiler.internal.as.codegen.DirectiveProcessor.traverse(DirectiveProcessor.java:193)
    at org.apache.royale.compiler.internal.as.codegen.ABCGenerator.generate(ABCGenerator.java:124)
    at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.handleABCBytesRequest(MXMLCompilationUnit.java:199)
    at org.apache.royale.compiler.internal.units.CompilationUnitBase.processABCBytesRequest(CompilationUnitBase.java:875)
    at org.apache.royale.compiler.internal.units.CompilationUnitBase.access$300(CompilationUnitBase.java:108)
    at org.apache.royale.compiler.internal.units.CompilationUnitBase$4$1.call(CompilationUnitBase.java:312)
    at org.apache.royale.compiler.internal.units.CompilationUnitBase$4$1.call(CompilationUnitBase.java:308)
    at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228)
    at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor$CallerRunsPolicy.rejectedExecution(ThreadPoolExecutor.java:2022)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
    at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
    at org.apache.royale.compiler.internal.units.requests.RequestMaker.getRequest(RequestMaker.java:188)
    at org.apache.royale.compiler.internal.units.CompilationUnitBase.getABCBytesRequest(CompilationUnitBase.java:623)
    at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.handleOutgoingDependenciesRequest(MXMLCompilationUnit.java:249)
    at org.apache.royale.compiler.internal.units.CompilationUnitBase.processOutgoingDependenciesRequest(CompilationUnitBase.java:891)
    at org.apache.royale.compiler.internal.units.CompilationUnitBase.access$500(CompilationUnitBase.java:108)
    at org.apache.royale.compiler.internal.units.CompilationUnitBase$6$1.call(CompilationUnitBase.java:387)
    at org.apache.royale.compiler.internal.units.CompilationUnitBase$6$1.call(CompilationUnitBase.java:383)
    at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228)
    at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by aharui** [comment]
If you get an error like this, try commenting out various parts of the MXML file until the error goes away, then try making a small test case with the last thing you commented out to prove that it is simply related to that one thing.  Then attach the sample source code.  We cannot act on reports that don't have source code.

**Comment by Harbs** [comment]
@pashminakazi Do you have a test case for this, or should we close the issue?
