### ISSUE TITLE
compiler omits expressions with dynamic object access

### ISSUE THREAD

**Issue by mrchnk** [apache/royale-compiler#69]
Compiler omits expression with both "." and "[]" access to dynamic `Object`.

```
var object: Object = { coordinate: [10, 20] };
var x: Number = object.coordinate[0];
```

That producing
```
var /** @type {Object} */ object = {coordinate:[10, 20]};
var /** @type {number} */ x = ;
```

I also created a minimal example project to reproduce that issue at https://github.com/mrchnk/royale-compiler-problems/tree/master/dynamic-object-access

I found that bug in npm distribution of compiler @apache-royale/royale-js@0.9.4
That problem persists in the nightly build of compiler 1723

**Comment by Harbs** [comment]
Interesting.

I tried adding the code to an MXML file and I get a NullPointerException.

````
<?xml version="1.0" encoding="utf-8"?>

<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:js="library://ns.apache.org/royale/basic" xmlns:ns1="*" applicationComplete="onComplete()">
    <fx:Script>
        <![CDATA[
            import org.apache.royale.test.Assert;

            private function onComplete():void{
                var object: Object = { coordinate : [ 10, 20 ] };
                var x: Number = object.coordinate[0];
                Assert.strictEqual(x, 10);
                trace("OK");                
            }
        ]]>
    </fx:Script>
    <js:valuesImpl>
        <js:SimpleCSSValuesImpl />
    </js:valuesImpl>
    <js:initialView>
    <js:View>
        <js:TextButton text="Click Me"/>
    </js:View>
    </js:initialView>
</js:Application>
````
Outputs:
````
test_project as: [test_project, org.apache.royale.test.Assert]
test_project mxml: [org.apache.royale.core.SimpleCSSValuesImpl, org.apache.royale.core.View, org.apache.royale.html.TextButton, test_project, org.apache.royale.core.Application, org.apache.royale.events.Event]
/test_project/src/test_project.mxml line 11 column 16 Error: Internal error in ASBlockWalker subsystem, when generating code for: /test_project/src/test_project.mxml line 11 column 16: java.lang.NullPointerException
	at org.apache.royale.compiler.internal.codegen.js.jx.VarDeclarationEmitter.emit(VarDeclarationEmitter.java:159)
	at org.apache.royale.compiler.internal.codegen.js.royale.JSRoyaleEmitter.emitVarDeclaration(JSRoyaleEmitter.java:716)
	at org.apache.royale.compiler.internal.codegen.as.ASBlockWalker.visitVariable(ASBlockWalker.java:278)
	at org.apache.royale.compiler.internal.visitor.as.ASNodeSwitch.handle(ASNodeSwitch.java:162)
	at org.apache.royale.compiler.internal.visitor.as.ASNodeHandler.handle(ASNodeHandler.java:85)
	at org.apache.royale.compiler.internal.visitor.as.BeforeAfterStrategy.handle(BeforeAfterStrategy.java:110)
	at org.apache.royale.compiler.internal.codegen.as.ASBlockWalker.walk(ASBlockWalker.java:159)
	at org.apache.royale.compiler.internal.codegen.js.jx.StatementEmitter.emit(StatementEmitter.java:40)
	at org.apache.royale.compiler.internal.codegen.js.jx.StatementEmitter.emit(StatementEmitter.java:29)
	at org.apache.royale.compiler.internal.codegen.js.JSEmitter.emitStatement(JSEmitter.java:323)
	at org.apache.royale.compiler.internal.codegen.js.royale.JSRoyaleEmitter.emitStatement(JSRoyaleEmitter.java:1004)
	at org.apache.royale.compiler.internal.codegen.as.ASBlockWalker.visitBlock(ASBlockWalker.java:349)
	at org.apache.royale.compiler.internal.visitor.as.ASNodeSwitch.handle(ASNodeSwitch.java:278)
	at org.apache.royale.compiler.internal.visitor.as.ASNodeHandler.handle(ASNodeHandler.java:85)
	at org.apache.royale.compiler.internal.visitor.as.BeforeAfterStrategy.handle(BeforeAfterStrategy.java:110)
	at org.apache.royale.compiler.internal.codegen.as.ASBlockWalker.walk(ASBlockWalker.java:159)
	at org.apache.royale.compiler.internal.codegen.as.ASEmitter.emitMethodScope(ASEmitter.java:867)
	at org.apache.royale.compiler.internal.codegen.js.jx.MethodEmitter.emit(MethodEmitter.java:145)
	at org.apache.royale.compiler.internal.codegen.js.royale.JSRoyaleEmitter.emitMethod(JSRoyaleEmitter.java:740)
	at org.apache.royale.compiler.internal.codegen.as.ASBlockWalker.visitFunction(ASBlockWalker.java:290)
	at org.apache.royale.compiler.internal.visitor.as.ASNodeSwitch.handle(ASNodeSwitch.java:152)
	at org.apache.royale.compiler.internal.visitor.as.ASNodeHandler.handle(ASNodeHandler.java:85)
	at org.apache.royale.compiler.internal.visitor.as.BeforeAfterStrategy.handle(BeforeAfterStrategy.java:110)
	at org.apache.royale.compiler.internal.codegen.as.ASBlockWalker.walk(ASBlockWalker.java:159)
	at org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyaleEmitter.emitScripts(MXMLRoyaleEmitter.java:1750)
	at org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyaleEmitter.emitDocument(MXMLRoyaleEmitter.java:709)
	at org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyaleBlockWalker.visitDocument(MXMLRoyaleBlockWalker.java:69)
	at org.apache.royale.compiler.internal.visitor.mxml.MXMLNodeSwitch.handle(MXMLNodeSwitch.java:86)
	at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.walk(MXMLBlockWalker.java:153)
	at org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyaleBlockWalker.visitFile(MXMLRoyaleBlockWalker.java:61)
	at org.apache.royale.compiler.internal.visitor.mxml.MXMLNodeSwitch.handle(MXMLNodeSwitch.java:92)
	at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.walk(MXMLBlockWalker.java:153)
	at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.visitCompilationUnit(MXMLBlockWalker.java:184)
	at org.apache.royale.compiler.internal.codegen.mxml.MXMLWriter.writeTo(MXMLWriter.java:71)
	at org.apache.royale.compiler.clients.MXMLJSCRoyale.compile(MXMLJSCRoyale.java:411)
	at org.apache.royale.compiler.clients.MXMLJSCRoyale._mainNoExit(MXMLJSCRoyale.java:265)
	at org.apache.royale.compiler.clients.MXMLJSCRoyale.mainNoExit(MXMLJSCRoyale.java:222)
	at org.apache.royale.compiler.clients.MXMLJSC._mainNoExit(MXMLJSC.java:365)
	at org.apache.royale.compiler.clients.MXMLJSC.mainNoExit(MXMLJSC.java:300)
	at org.apache.royale.compiler.clients.MXMLJSC.staticMainNoExit(MXMLJSC.java:259)
	at org.apache.royale.compiler.clients.MXMLJSC.main(MXMLJSC.java:241)
````

**Comment by mrchnk** [comment]
I can confirm that my issue is resolved in build number 1735

**Comment by Harbs** [comment]
Great.

One more tip regarding dynamic objects:
`-js-dynamic-access-unknown-members=true` Causes the compiler to output all dynamic objects with bracket notation and quoted object literals. This prevents the Closure compiler from minifying the dynamic variable names. This is important if the names are significant -- such as predefined data structures and JSON.
