### ISSUE TITLE
Assign to int or uint variable does not convert Number from floating point to integer

### ISSUE THREAD

**Issue by joshtynjala** [apache/royale-compiler#74]
A developer using `int` or `uint` will never want floating point values. Otherwise, they'd be using `Number` instead. We need to ensure that `int` and `uint` behave correctly in our generated JavaScript.

Current behavior:

``` actionscript
var integer:int = -10.25;
trace("init with literal:", integer); //-10.25
integer = -10.25;
trace("assign with literal:", integer); //-10.25
integer = -10.25 + -5;
trace("add with literals:", integer); //-15.25

var number:Number = -10.25;
var number2:Number = -5;

var integer2:int = number;
trace("init with Number:", integer2); //-10.25
integer2 = number;
trace("assign with Number:", integer2); //-10.25
integer2 = number + number2;
trace("add with Number:", integer2); //-15.25
```

Expected behavior:

``` actionscript
var integer:int = -10.25;
trace("init with literal:", integer); //-10
integer = -10.25;
trace("assign with literal:", integer); //-10
integer = -10.25 + -5;
trace("add with literals:", integer); //-15

var number:Number = -10.25;
var number2:Number = -5;

var integer2:int = number;
trace("init with Number:", integer2); //-10
integer2 = number;
trace("assign with Number:", integer2); //-10
integer2 = number + number2;
trace("add with Number:", integer2); //-15
```

To fix, the emitter could output `Language._int()`. However, we probably want to avoid a function call, so maybe just inline the same operation:

``` js
var integer = (-10.25) >> 0;
```

(The parentheses will be needed for complex expressions, but we might be able to remove them sometimes... or maybe Closure compiler will do it for us?) 

Some alternate syntax options that should work too (however, we should probably be consistent with `Language._int()`:

``` js
var integer = (-10.25) | 0;
```

``` js
var integer = ~~(-10.25);
```

`Math.floor()` should definitely be avoided. It does not simply drop the decimal part. It rounds down, which would give an incorrect value for negative floating point numbers. `-10.25` would become `-11` with `Math.floor()`

**Comment by carlosrovira** [comment]
Hi Josh,

this commit is generating the following problem when we compile our app:

> RangeError: Maximum call stack size exceeded
> Language.js:115
>     at String.toString (<anonymous>)
>     at Function.org.apache.royale.utils.Language.string (/Users/carlosrovira/Dev/Codeoscopic/Source/sgc/webapp/src/main/webapp/javascript/bin/js-debug/org/apache/royale/utils/Language.js:115:80)
>     at Function.org.apache.royale.utils.Language.string (/Users/carlosrovira/Dev/Codeoscopic/Source/sgc/webapp/src/main/webapp/javascript/bin/js-debug/org/apache/royale/utils/Language.js:115:44)
>     at Function.org.apache.royale.utils.Language.string (/Users/carlosrovira/Dev/Codeoscopic/Source/sgc/webapp/src/main/webapp/javascript/bin/js-debug/org/apache/royale/utils/Language.js:115:44)
>     at Function.org.apache.royale.utils.Language.string (/Users/carlosrovira/Dev/Codeoscopic/Source/sgc/webapp/src/main/webapp/javascript/bin/js-debug/org/apache/royale/utils/Language.js:115:44)
>     at Function.org.apache.royale.utils.Language.string (/Users/carlosrovira/Dev/Codeoscopic/Source/sgc/webapp/src/main/webapp/javascript/bin/js-debug/org/apache/royale/utils/Language.js:115:44)
>     at Function.org.apache.royale.utils.Language.string (/Users/carlosrovira/Dev/Codeoscopic/Source/sgc/webapp/src/main/webapp/javascript/bin/js-debug/org/apache/royale/utils/Language.js:115:44)
>     at Function.org.apache.royale.utils.Language.string (/Users/carlosrovira/Dev/Codeoscopic/Source/sgc/webapp/src/main/webapp/javascript/bin/js-debug/org/apache/royale/utils/Language.js:115:44)
>     at Function.org.apache.royale.utils.Language.string (/Users/carlosrovira/Dev/Codeoscopic/Source/sgc/webapp/src/main/webapp/javascript/bin/js-debug/org/apache/royale/utils/Language.js:115:44)
>     at Function.org.apache.royale.utils.Language.string (/Users/carlosrovira/Dev/Codeoscopic/Source/sgc/webapp/src/main/webapp/javascript/bin/js-debug/org/apache/royale/utils/Language.js:115:44)
> Failed to load resource: the server responded with a status of 404 (No Encontrado) 

Could you take a look on what could be the problem?

Thanks in advance for your help

Carlos

**Comment by Harbs** [comment]
I think the bug was in Language.string. I just committed a fix for that.

**Comment by Harbs** [comment]
It looks like the compiler has a bug. It adds the Language.string call even when using an as cast in a ternary expression. I made a temporary change to Language.string to work-around the issue in the meantime.

**Comment by carlosrovira** [comment]
Thanks Harbs, I tried and your temp change solved the issue for now. Thanks!

**Comment by aharui** [comment]
How hard would it be to add null handling so the compiler doesn't try to needlessly wrap the ternary expression?

**Comment by joshtynjala** [comment]
@aharui I haven't looked at the code where the type of a ternary expression is resolved, but I suspect that it's pretty basic. I assume that it's like this: If both results are of the same type, then use that type for the whole expression. If both results are different types, then use * for the type.

We should be able to add a special case where, if one side is null and the other side is a nullable type (basically, anything except boolean, number, int, uint, and *), return that nullable type for the whole ternary expression.

However, there's one other wrinkle. Copying the code below for context:

``` actionscript
function string(value:*):String
{
	return value == null ? null : value.toString();
}
```

We'd still need a cast in this particular case. Since value is typed as *, any properties or methods called on it are also * from the compiler's perspective. , the code above would get wrapped. We'd need this at least to ensure that the compiler knows that the toString() return type is String:

``` actionscript
function string(value:*):String
{
	return value == null ? null : (value as Object).toString();
}
```

**Comment by aharui** [comment]
Does value have to be "*"?  Why can't it be Object?

**Comment by joshtynjala** [comment]
Actually, yes, I think that the value parameter could be Object instead of *. Since undefined will be changed to null in the result, any automatic coercion from undefined to null earlier in the process won't matter.

**Comment by joshtynjala** [comment]
Hmmm... in the AS3 code generated by externc, Object.as does not define toString(). The compiler is seeing the call to toString() as dynamic access, so the return type is assumed to be * instead.

I think we'd need to define toString() like this in Object.as generated by externc:

```
AS3 function toString(radix:* = 10):String { return null; }
```

It's defined in the AS3 namespace like that in playerglobal.swc.

**Comment by joshtynjala** [comment]
TernaryOperatorNode.resolveType() looks like this:

``` actionscript
ITypeDefinition leftType = getLeftOperandNode().resolveType(project);
ITypeDefinition rightType = getRightOperandNode().resolveType(project);
if (leftType == rightType)
    return leftType;

return project.getBuiltinType(BuiltinType.ANY_TYPE);
```

This would allow us to resolve a nullable type instead:

``` actionscript
ITypeDefinition leftType = getLeftOperandNode().resolveType(project);
ITypeDefinition rightType = getRightOperandNode().resolveType(project);
if (leftType == rightType)
    return leftType;

ITypeDefinition nullType = project.getBuiltinType(BuiltinType.NULL);
ITypeDefinition typeToCheckForNullable = null;
if (nullType.equals(leftType))
{
    typeToCheckForNullable = rightType;
}
else if (nullType.equals(rightType))
{
    typeToCheckForNullable = leftType;
}
if (typeToCheckForNullable != null)
{
    if (!project.getBuiltinType(BuiltinType.BOOLEAN).equals(typeToCheckForNullable)
            && !project.getBuiltinType(BuiltinType.NUMBER).equals(typeToCheckForNullable)
            && !project.getBuiltinType(BuiltinType.INT).equals(typeToCheckForNullable)
            && !project.getBuiltinType(BuiltinType.UINT).equals(typeToCheckForNullable))
    {
        return typeToCheckForNullable;
    }
}
return project.getBuiltinType(BuiltinType.ANY_TYPE);
```

**Comment by joshtynjala** [comment]
> I think we'd need to define toString() like this in Object.as generated by externc:

My mistake. That's the definition of Number.toString(), obviously. In playerglobal.swc, Object.toString() doesn't exist either. That could make things very tricky.

**Comment by joshtynjala** [comment]
Found an option with no casting at all, keeping the value parameter typed as *, and no compiler changes:

``` actionscript
function string(value:*):String
{
	if(value == null)
		return null;
	return String(value);
}
```

String() has a quirk where it returns null as "null", but we're accounting for that, so it will simply end up calling toString() on the object.

**Comment by aharui** [comment]
Again, my concern is about existing code migrating from Flex.  I think some other existing code will be using a ternary expression and it will be better if we could learn to not wrap it in conversion code.

In the compiler, there are already some special cases for Object.  See ClassReference.java.  There might be other places.  I thought Object.toString was also in the AS3 namespace in playerglobal and not defined in js.swc so the compiler was special casing Object.toString.  You could also debug a simple call to Object.toString() (which I believe should work) and see how it is resolved in the compiler.

**Comment by aharui** [comment]
Does String() call the toString()?  Is this new pattern as small and fast or does String() have more overhead?  I would think it would have more overhead to check what type the value is, but I could be wrong.

**Comment by Harbs** [comment]
Here's a nice summary of the different methods of converting to string:


Performance-wise toString() seems to be the poorest performer and string concatenation seems to be the best:
https://jsperf.com/cast-to-string/2

Possibly, we should do this:
````
		static public function string(value:*):String
		{
			if(value == null)
				return value as String;
			return "" + value;
		}
````

**Comment by Harbs** [comment]
I think we should return `value` rather than `null` to preserve `undefined` if it's `undefined` instead of `null`.

**Comment by joshtynjala** [comment]
It's coercing to a value that can be stored in String. undefined should not be preserved.

**Comment by Harbs** [comment]
Makes sense.

FYI, I just ran that jsperf across Chrome, Firefox and Safari.

String concatenation is consistently fastest across Mac browsers. (I have not checked Windows.)
String(val) vs. val.toString() varies from browser to browser. Safari seems to be pretty bad with String(val).

It seems to me that we should use:
````
static public function string(value:*):String
{
	if(value == null)
		return null;
	return "" + value;
}
````

**Comment by joshtynjala** [comment]
On Windows, and I'm seeing that string concatenation is fastest too.

**Comment by greg-dove** [comment]
I'm not exactly sure yet what caused it, but recent changes have broken something in (I think) AMFBinaryData (*or perhaps in related networking classes*). I will investigate tomorrow and try to understand what exactly the issues are. I locally reverted Josh's last compiler commit, but that may not be related, because I only got things working correctly again by also locally rolling back as-js (I arbitrarily chose https://github.com/apache/royale-asjs/commit/c4bf49b967e150c616ac2773b0d919dcdc190734 ). I suspect it may have something to do with these various changes, but will need to try to verify tomorrow. I just wanted to at least flag the possibility that this might need more attention, for now.

**Comment by carlosrovira** [comment]
Hi, I can confirm that we have a regression in AMF. At least for Dates (that in the end are numbers). I think you're near but still need something to fix. Seems AMFBinaryData is right, so although I can't ensure seems a bug caused by latest changes. In my case to continue working I need to go in compiler to 6a85bc1cd0c09e4ca07cf221a55ec9dd13e5d63c commit (just before this change) but I can go stay in latest royale-asjs develop current commit at the time of posting this (a3aa637402ec2e3d71d370f2c717a0d579c23c88). Hope you'll find the issue and so we could continue updating royale-compiler! :) thanks for working on this.

**Comment by Harbs** [comment]
@carlosrovira Do you think you can try and track down the source of the problem? I have no way to test AMF.

I'd look out for Language.string calls and anywhere something is declared as an int or uint.

**Comment by carlosrovira** [comment]
Hi @Harbs, before Greg close in his day, he told me that seems the problem was not in AMFBinaryData itself, since that was working right before the change. Of course, thinking that serialization is ok, and I think is ok, since it was working before. For that reason seems that the issue is located in the compiler.

In order to help from my side, I can test whatever you want, but need some guidance since I don't see where I can look.

Other way is to use our SampleAMFWebApp and add a method that send a simple date and retrieve in the examples/mxroyale/RemoteObjectAMFTest, you should get a different Date than the one sent by java. I can prepare this example to do this if you want so you can analyze it locally and get straight to the issue.

**Comment by Harbs** [comment]
I'd step through the code where date is being encoded/decoded and compare.

You can narrow down where you're looking by looking at the differences between the working .js files and the non-working ones.

**Comment by joshtynjala** [comment]
> Of course, thinking that serialization is ok, and I think is ok, since it was working before. For that reason seems that the issue is located in the compiler.

It's not necessarily an issue in the compiler. AMFBinaryData may have been "working" before because it was relying on the incorrect output from the compiler. Previously the compiler wasn't coercing types correctly for function parameters and return values, which meant that variables may have been storing values that would be impossible in Flash. After my changes, the JS output should behave closer to Flash. Fixing this issue in the compiler may have finally exposed a bug in AMFBinaryData.

I'm not saying that it's impossible that there's a bug in my changes. However, don't rule out a bug in AMFBinaryData yet.

> In order to help from my side, I can test whatever you want, but need some guidance since I don't see where I can look.

As Harbs said, you should look at how the generated JS looks before and after the changes. That should help narrow down which parts of the code were affected. In particular, the places where an argument is passed to a function or where a function returns will be most relevant.

Also consider looking at conversions between int, uint, and Number.

For instance, I see that readScriptObject() has this line:

``` actionscript
var ref:int = this.readUInt29();
```

All other calls to readUint29() in the same file store the result in a uint instead of an int. That may not be the bug, but I wonder if it's correct or not.

> you should get a different Date than the one sent by java

Can you give an example of a correct date and the incorrect data that you see instead?

**Comment by carlosrovira** [comment]
Hi Josh,

I'm going to put traces to see the right date value, and then the same with your changes to post here both dates. In the meanwhile, could you see the points in AMFBinaryData that could be problematic like the one you already posted? (I mean var ref:int = this.readUInt29();).

Thanks

**Comment by carlosrovira** [comment]
Just talked with Greg, and he's going to check this so to avoid duplicating work he'll be in touch with you. Thanks

**Comment by greg-dove** [comment]
Interestingly, some static consts did not seem to be 'coerced', but probably should have been, example:
`public static const POW_2_52N:int = Math.pow(2, -52);`
I will change the type of those to Number in the code as well, because they are outside the uint/int ranges.
Slightly OT: I assume these consts might be optimized for release build by GCC to use 'compile-time' results of the Math call, if they are not maybe we could do that in royale compiler-jx at some point.

**Comment by joshtynjala** [comment]
> Interestingly, some static consts did not seem to be 'coerced', but probably should have been, example:
> public static const POW_2_52N:int = Math.pow(2, -52);

That definitely sounds like a bug. I'll check it out.

**Comment by greg-dove** [comment]
My local changes in AMFBinaryData seem to restore things. I will verify it with use in Carlos' app today and push those changes towards my EOD to asjs if I think I got all the obvious ones. I made quite a few int-to-uint changes throughout. fyi Another thing I do see in the compiler output now are things like this:
`for (i = (0) >>> 0; i < l; i++) {`
maybe the coercion can be avoided for literal values (like zero) or maybe GCC strips it out (not sure - if it does, then no problem)

**Comment by joshtynjala** [comment]
> fyi Another thing I do see in the compiler output now are things like this:
> for (i = (0) >>> 0; i < l; i++) {
> maybe the coercion can be avoided for literal values (like zero) or maybe GCC strips it out (not sure - if it does, then no problem)

If I remember correctly, it currently won't coerce integer literals assigned to int, but it will when assigned to uint. I agree that it would be ideal if both were not coerced, as long as the literal value is in range for the type.

**Comment by joshtynjala** [comment]
I should also add, thanks for looking into this @greg-dove! Much appreciated.

**Comment by aharui** [comment]
IMO, that's a bug in the compiler.  The parentheses are in the wrong place.  The framework code should not be refactored to workaround it.  Hopefully @joshtynjala will have time to fix it.

**Comment by joshtynjala** [comment]
The `)` was indeed in the wrong location. We didn't notice before I added int/uint coercion because the existing coercions all ended in `)` too, so the output would have been the same either way.

**Comment by Harbs** [comment]
It looks like the int coercions is a little too eager and any arithmetic causes coercions:
In a method with the following signature:
`function getAtomBounds(atomIndex:int):Rectangle`
`var nextIdx:int = atomIndex+1;`
compiles to:
`  var /** @type {number} */ nextIdx = (atomIndex + 1) >> 0;`
When it should only be:
`  var /** @type {number} */ nextIdx = atomIndex + 1;`

**Comment by Harbs** [comment]
The same is true for subtracting and int from an int.

Coercions should only happen when dividing one int with another or arithmetic with an int and a floating point number. (i.e. a Number or float literal)

**Comment by joshtynjala** [comment]
All numeric literals resolve to Number, even if they're an integer. I added a special case for assigning a simple numeric literal integer, but expressions are treated as Number.

I should be able to manually crawl a more complex expression to check that all of these are true:

1) numeric literals are all integers
2) variables are all integers
3) functions only return integers
4) only the allowed operators are used
5) any other sub-expressions resolve to int (this may have some more edge cases, but we can address them as they're found)

Example of a complex expression that should be allowed:

``` as3
(((1 + myInt) * 4) - 2 + getInt()) * 9
```

**Comment by Harbs** [comment]
I'd addd to your list:
6. There is no division in the expression

**Comment by aharui** [comment]
Might be time for a compiler option for this as well.

**Comment by joshtynjala** [comment]
> 6. There is no division in the expression

That falls under "only the allowed operators are used". Division would not be one of the operators that could skip the coercion code.

**Comment by joshtynjala** [comment]
> It looks like the int coercions is a little too eager and any arithmetic causes coercions

Actually, after thinking on this some more, I realized that the coercion there is necessary. Part of the coercion is ensuring that the value stays in the allowed range for int. Arithmetic could cause the variable to overflow out of range.

This is easier to see with uint.

```
var myUint:uint = 0;
myUint = myUint - 1;
```

Without coercion to enforce the range, this uint would hold a negative value.

**Comment by Harbs** [comment]
Hmm. Hard problem...

The 99% case will not cause overflow. Always forcing the coercion can have some serious performance ramifications in performance sensitive loops.

Any suggestions on preventing performance problems?

**Comment by Harbs** [comment]
Maybe a compiler flag for enforcing int and uint ranges and some notation to override the default on a case by case basis?

**Comment by Harbs** [comment]
What happens when an int overflows in Flash?

**Comment by joshtynjala** [comment]
I don't mind if we're not strict about int ranges, since it's rare to matter. For uint, I think that it's important to ensure that it doesn't go negative, but we don't need to be strict if it will definitely remain positive as the result of an expression. There could be a compiler option for maximum strictness, I guess.

Integers that overflow roll around to the other end of the allowed range. So, the maximum positive int + 1 continues on from the negative bound. Similarly, - 1 on the negative side starts over from the positive side. The operators that we currently use for coercion should behave correctly in that regard.

**Comment by aharui** [comment]
Just add Compiler Options for these.  Give folks a choice as to how hard the compiler thinks and what kind of code it generates.  Bonus if you can add suppressible warnings for when the compiler encountered an expression that has some chance of not doing what Flash would do.

**Comment by Harbs** [comment]
Regarding the Language.string discussion, I just discovered a difference between `val.toString()` and `"" + val`:
`"" + val` implicitly calls `val.valueOf()` instead of `val.toString()`. If there is a difference in behavior between what you get from `valueOf()` and `toString()`, the two results will not be identical. I just ran into this with XML where the new code was causing the XML `valueOf` to be called and it was returning 0 instead of a space. I guess it's good we found the bug in XML, but it made me realize this difference.

I'm not sure which behavior is more pure. I'm leaning towards saying that `valueOf` is better because Language.string is used for implicit coercions which the implementation of `valueOf` was designed for.

I'm struggling to find a case where any of this should matter though... ;)
